
package client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "OrgTreeDataService", targetNamespace = "http://xinwis/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface OrgTreeDataService {


    /**
     * 
     */
    @WebMethod(operationName = "SayHiDefault")
    @Action(input = "http://xinwis/OrgTreeDataService/SayHiDefaultRequest", output = "http://xinwis/OrgTreeDataService/SayHiDefaultResponse")
    public void sayHiDefault();

    /**
     * 
     * @param clientTime
     * @return
     *     returns int
     */
    @WebMethod(operationName = "CheckTime")
    @WebResult(name = "valid", partName = "valid")
    @Action(input = "http://xinwis/OrgTreeDataService/CheckTimeRequest", output = "http://xinwis/OrgTreeDataService/CheckTimeResponse")
    public int checkTime(
            @WebParam(name = "clientTime", partName = "clientTime")
                    XMLGregorianCalendar clientTime);

    /**
     * 
     * @param name
     */
    @WebMethod(operationName = "SayHi")
    @Action(input = "http://xinwis/OrgTreeDataService/SayHiRequest", output = "http://xinwis/OrgTreeDataService/SayHiResponse")
    public void sayHi(
            @WebParam(name = "name", partName = "name")
                    String name);

}
